package fr.mateoox600.game.lua.bindings;

import com.raylib.java.core.input.Keyboard;
import fr.mateoox600.game.lua.LuaPlatform;
import se.krka.kahlua.vm.KahluaTable;

public class KeyboardButton {

    public static KahluaTable getKeyboardButtonTable(LuaPlatform platform) {
        KahluaTable table = platform.newTable();

        table.rawset("KEY_APOSTROPHE", (double) Keyboard.KEY_APOSTROPHE);
        table.rawset("KEY_COMMA", (double) Keyboard.KEY_COMMA);
        table.rawset("KEY_MINUS", (double) Keyboard.KEY_MINUS);
        table.rawset("KEY_PERIOD", (double) Keyboard.KEY_PERIOD);
        table.rawset("KEY_SLASH", (double) Keyboard.KEY_SLASH);
        table.rawset("KEY_ZERO", (double) Keyboard.KEY_ZERO);
        table.rawset("KEY_ONE", (double) Keyboard.KEY_ONE);
        table.rawset("KEY_TWO", (double) Keyboard.KEY_TWO);
        table.rawset("KEY_THREE", (double) Keyboard.KEY_THREE);
        table.rawset("KEY_FOUR", (double) Keyboard.KEY_FOUR);
        table.rawset("KEY_FIVE", (double) Keyboard.KEY_FIVE);
        table.rawset("KEY_SIX", (double) Keyboard.KEY_SIX);
        table.rawset("KEY_SEVEN", (double) Keyboard.KEY_SEVEN);
        table.rawset("KEY_EIGHT", (double) Keyboard.KEY_EIGHT);
        table.rawset("KEY_NINE", (double) Keyboard.KEY_NINE);
        table.rawset("KEY_SEMICOLON", (double) Keyboard.KEY_SEMICOLON);
        table.rawset("KEY_EQUAL", (double) Keyboard.KEY_EQUAL);
        table.rawset("KEY_A", (double) Keyboard.KEY_A);
        table.rawset("KEY_B", (double) Keyboard.KEY_B);
        table.rawset("KEY_C", (double) Keyboard.KEY_C);
        table.rawset("KEY_D", (double) Keyboard.KEY_D);
        table.rawset("KEY_E", (double) Keyboard.KEY_E);
        table.rawset("KEY_F", (double) Keyboard.KEY_F);
        table.rawset("KEY_G", (double) Keyboard.KEY_G);
        table.rawset("KEY_H", (double) Keyboard.KEY_H);
        table.rawset("KEY_I", (double) Keyboard.KEY_I);
        table.rawset("KEY_J", (double) Keyboard.KEY_J);
        table.rawset("KEY_K", (double) Keyboard.KEY_K);
        table.rawset("KEY_L", (double) Keyboard.KEY_L);
        table.rawset("KEY_M", (double) Keyboard.KEY_M);
        table.rawset("KEY_N", (double) Keyboard.KEY_N);
        table.rawset("KEY_O", (double) Keyboard.KEY_O);
        table.rawset("KEY_P", (double) Keyboard.KEY_P);
        table.rawset("KEY_Q", (double) Keyboard.KEY_Q);
        table.rawset("KEY_R", (double) Keyboard.KEY_R);
        table.rawset("KEY_S", (double) Keyboard.KEY_S);
        table.rawset("KEY_T", (double) Keyboard.KEY_T);
        table.rawset("KEY_U", (double) Keyboard.KEY_U);
        table.rawset("KEY_V", (double) Keyboard.KEY_V);
        table.rawset("KEY_W", (double) Keyboard.KEY_W);
        table.rawset("KEY_X", (double) Keyboard.KEY_X);
        table.rawset("KEY_Y", (double) Keyboard.KEY_Y);
        table.rawset("KEY_Z", (double) Keyboard.KEY_Z);
        table.rawset("KEY_SPACE", (double) Keyboard.KEY_SPACE);
        table.rawset("KEY_ESCAPE", (double) Keyboard.KEY_ESCAPE);
        table.rawset("KEY_ENTER", (double) Keyboard.KEY_ENTER);
        table.rawset("KEY_TAB", (double) Keyboard.KEY_TAB);
        table.rawset("KEY_BACKSPACE", (double) Keyboard.KEY_BACKSPACE);
        table.rawset("KEY_INSERT", (double) Keyboard.KEY_INSERT);
        table.rawset("KEY_DELETE", (double) Keyboard.KEY_DELETE);
        table.rawset("KEY_RIGHT", (double) Keyboard.KEY_RIGHT);
        table.rawset("KEY_LEFT", (double) Keyboard.KEY_LEFT);
        table.rawset("KEY_DOWN", (double) Keyboard.KEY_DOWN);
        table.rawset("KEY_UP", (double) Keyboard.KEY_UP);
        table.rawset("KEY_PAGE_UP", (double) Keyboard.KEY_PAGE_UP);
        table.rawset("KEY_PAGE_DOWN", (double) Keyboard.KEY_PAGE_DOWN);
        table.rawset("KEY_HOME", (double) Keyboard.KEY_HOME);
        table.rawset("KEY_END", (double) Keyboard.KEY_END);
        table.rawset("KEY_CAPS_LOCK", (double) Keyboard.KEY_CAPS_LOCK);
        table.rawset("KEY_SCROLL_LOCK", (double) Keyboard.KEY_SCROLL_LOCK);
        table.rawset("KEY_NUM_LOCK", (double) Keyboard.KEY_NUM_LOCK);
        table.rawset("KEY_PRINT_SCREEN", (double) Keyboard.KEY_PRINT_SCREEN);
        table.rawset("KEY_PAUSE", (double) Keyboard.KEY_PAUSE);
        table.rawset("KEY_F1", (double) Keyboard.KEY_F1);
        table.rawset("KEY_F2", (double) Keyboard.KEY_F2);
        table.rawset("KEY_F3", (double) Keyboard.KEY_F3);
        table.rawset("KEY_F4", (double) Keyboard.KEY_F4);
        table.rawset("KEY_F5", (double) Keyboard.KEY_F5);
        table.rawset("KEY_F6", (double) Keyboard.KEY_F6);
        table.rawset("KEY_F7", (double) Keyboard.KEY_F7);
        table.rawset("KEY_F8", (double) Keyboard.KEY_F8);
        table.rawset("KEY_F9", (double) Keyboard.KEY_F9);
        table.rawset("KEY_F10", (double) Keyboard.KEY_F10);
        table.rawset("KEY_F11", (double) Keyboard.KEY_F11);
        table.rawset("KEY_F12", (double) Keyboard.KEY_F12);
        table.rawset("KEY_LEFT_SHIFT", (double) Keyboard.KEY_LEFT_SHIFT);
        table.rawset("KEY_LEFT_CONTROL", (double) Keyboard.KEY_LEFT_CONTROL);
        table.rawset("KEY_LEFT_ALT", (double) Keyboard.KEY_LEFT_ALT);
        table.rawset("KEY_LEFT_SUPER", (double) Keyboard.KEY_LEFT_SUPER);
        table.rawset("KEY_RIGHT_SHIFT", (double) Keyboard.KEY_RIGHT_SHIFT);
        table.rawset("KEY_RIGHT_CONTROL", (double) Keyboard.KEY_RIGHT_CONTROL);
        table.rawset("KEY_RIGHT_ALT", (double) Keyboard.KEY_RIGHT_ALT);
        table.rawset("KEY_RIGHT_SUPER", (double) Keyboard.KEY_RIGHT_SUPER);
        table.rawset("KEY_KB_MENU", (double) Keyboard.KEY_KB_MENU);
        table.rawset("KEY_LEFT_BRACKET", (double) Keyboard.KEY_LEFT_BRACKET);
        table.rawset("KEY_BACKSLASH", (double) Keyboard.KEY_BACKSLASH);
        table.rawset("KEY_RIGHT_BRACKET", (double) Keyboard.KEY_RIGHT_BRACKET);
        table.rawset("KEY_GRAVE", (double) Keyboard.KEY_GRAVE);
        table.rawset("KEY_KP_0", (double) Keyboard.KEY_KP_0);
        table.rawset("KEY_KP_1", (double) Keyboard.KEY_KP_1);
        table.rawset("KEY_KP_2", (double) Keyboard.KEY_KP_2);
        table.rawset("KEY_KP_3", (double) Keyboard.KEY_KP_3);
        table.rawset("KEY_KP_4", (double) Keyboard.KEY_KP_4);
        table.rawset("KEY_KP_5", (double) Keyboard.KEY_KP_5);
        table.rawset("KEY_KP_6", (double) Keyboard.KEY_KP_6);
        table.rawset("KEY_KP_7", (double) Keyboard.KEY_KP_7);
        table.rawset("KEY_KP_8", (double) Keyboard.KEY_KP_8);
        table.rawset("KEY_KP_9", (double) Keyboard.KEY_KP_9);
        table.rawset("KEY_KP_DECIMAL", (double) Keyboard.KEY_KP_DECIMAL);
        table.rawset("KEY_KP_DIVIDE", (double) Keyboard.KEY_KP_DIVIDE);
        table.rawset("KEY_KP_MULTIPLY", (double) Keyboard.KEY_KP_MULTIPLY);
        table.rawset("KEY_KP_SUBTRACT", (double) Keyboard.KEY_KP_SUBTRACT);
        table.rawset("KEY_KP_ADD", (double) Keyboard.KEY_KP_ADD);
        table.rawset("KEY_KP_ENTER", (double) Keyboard.KEY_KP_ENTER);
        table.rawset("KEY_KP_EQUAL", (double) Keyboard.KEY_KP_EQUAL);

        return table;
    }

}
